### PR TITLE
Created Project overview Components

### PR DESCRIPTION
**Pull request by KevinLaCarrubba**
- Created the Dashboard Page's projectsOverview component
- Added the ability to fetch clients to `views/dashboard/index.tsx` under the function `getAllClients`
- Created a getAllClients query to match schema
- Added a `getAllClients`slice to the redux store
- Created a `dashboard` folder in pages
- Moved `dashboard.tsx` to this folder and renamed it `index.tsx`
- `dashboard` contains `projects/overview`

***Side Quest***
-added a key of `index` to userOverview map to rid error of "aDd ThE fUcKiNg kEy oR sEe tHiS fUcKiNg rEd MesSaGe"

### CODE REVIEW

**Comment by arfusop** [comment]
Task linked: [CU-46qkt0a Create the Projects Overview display Component for the Dashboard page](https://app.clickup.com/t/46qkt0a)

**Review by arfusop — CHANGES_REQUESTED** [review]
Very good overall. One or two optimization things, and then let's switch the `projects` focus for the redux store and other parts to be client focused instead. The reason being, for the Project overview display component, yes the focus is projects. But the API call is fetching all clients data, not just project data. So this call you added will be providing data for Projects, and for Clients in general, feeding multiple components. Client has Projects, Meetings, etc

**Review by arfusop — CHANGES_REQUESTED** [review]
Small things

**Review by arfusop — CHANGES_REQUESTED** [review]
One tiny change lol

**Review by arfusop — APPROVED** [review]

**Review by SamiFdev — APPROVED** [review]

**Pull request merged**
